FROM php:fpm-stretch

RUN apt-get update && apt-get install -y

RUN apt-get update && apt-get install -y wget git unzip \
    && pecl install xdebug-2.7.1 \
    && docker-php-ext-enable xdebug

RUN apt-get update && apt-get install -y --no-install-recommends \
wget \
git \
unzip \
zlib1g-dev \
libxml2-dev \
libzip-dev \
&& pecl install xdebug-2.9.6 \
&& docker-php-ext-install \
zip \
intl \
mysqli \
pdo pdo_mysql \
&& docker-php-ext-enable xdebug

ADD ./php.ini /usr/local/etc/php/php.ini

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY app/ /var/www/app
WORKDIR /var/www/app/
