version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - 8001:80
    networks:
      - symfony
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_DATABASE: test-project-db
      MYSQL_USER: test-project-user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3320:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28